#!/usr/bin/env php
<?php
// Load the autoloader
require_once(__DIR__."/vendor/autoload.php");

// Require the config
if(file_exists(__DIR__."/config.php"))
	require_once(__DIR__."/config.php");
else
	throw new Exception("config.php not found (you might wanna start by copying config_new.php)");

$app = new \Cilex\Application('projectRena');

$tasks = scandir(__DIR__ . "/src/Tasks/");
foreach($tasks as $task)
{
    if(!preg_match("/^(.+)\\.php$/", $task, $match))
        continue;

    if(isset($match[1]))
    {
        $taskName = $match[1];
        $import = "\\ProjectRena\\Tasks\\" . $taskName;
        $app->command(new $import());
    }
}

// Phinx Commands (Sadly they're not marked properly)
$app->command(new \Phinx\Console\Command\Init());
$app->command(new \Phinx\Console\Command\Create());
$app->command(new \Phinx\Console\Command\Migrate());
$app->command(new \Phinx\Console\Command\Rollback());
$app->command(new \Phinx\Console\Command\Status());
$app->command(new \Phinx\Console\Command\Test());

$app->run();